---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: chintan-runner-autoscaler
  namespace: ghar-controller
spec:
  scaleDownDelaySecondsAfterScaleOut: 10
  scaleTargetRef:
    name: chintan-runner
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - flux-firefly
        - github-action-runner
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: chintan-runner
  namespace: ghar-controller
spec:
  replicas: 1
  template:
    spec:
      labels:
        - "docker-runner"
      organization: improwised
      image: improwised/ghar-image:feat-add-buildah-f157dd9-1667219679
      dockerRegistryMirror: http://registry-cache:5000
      dockerdWithinRunnerContainer: true
      env:
        - name: RUNNER_FEATURE_FLAG_EPHEMERAL
          value: "true"
      resources:
        requests:
          cpu: 200m
          memory: 400Mi
        limits:
          cpu: 1500m
          memory: 4Gi
      volumeMounts:
        - name: cache
          mountPath: /gha-cache
      volumes:
        - name: cache
          hostPath:
            path: /tmp/gha-cache
      initContainers:
        - name: link
          image: improwised/ghar-image:feat-add-buildah-f157dd9-1667219679
          command: ["/bin/bash"]
          args:
            - "-cex"
            - |
              chown runner:runner -cR /gha-cache
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: cache
              mountPath: /gha-cache
